### ISSUE TITLE
Error on building project that use MBLMetaWearManager

### ISSUE THREAD

**Issue by ravimbhatt** [mbientlab/Metawear-SwiftStarter#1]
I am new to swift and trying to use it to connect to metawear. 

for the code below: 

override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        let manager  = MBLMetaWearManager.sharedManager()
        
        manager.startScanForMetaWearsWithHandler { handler -> Void in
            print("sss")
        }

    }

we get this error error: 

ld: warning: ignoring file /Metawear-SwiftStarter/Pods/Metawear-iOSAPI/MetaWear.framework/MetaWear, missing required architecture x86_64 in file /Metawear-SwiftStarter/Pods/Metawear-iOSAPI/MetaWear.framework/MetaWear (2 slices)
ld: warning: object file (/Library/Developer/Xcode/DerivedData/SwiftStarter-cmljeydlxxyhnnaurowyytphdhrh/Build/Products/Debug-iphonesimulator/libPods-SwiftStarter.a(Pods-SwiftStarter-dummy.o)) was built for newer iOS version (9.0) than being linked (7.1)
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_MBLMetaWearManager", referenced from:
      type metadata accessor for ObjectiveC.MBLMetaWearManager in ViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by ravimbhatt** [comment]
correct code is:

let manager  = MBLMetaWearManager.sharedManager()
manager.startScanForMetaWearsWithHandler { (array:[AnyObject]?)  in
            print(array)
}

still the same error.

**Comment by sschiffli** [comment]
You must build for iPhone, not the simulator.  There is no bluetooth support in the simulator, sorry :(

**Comment by ravimbhatt** [comment]
okay. got it. missed the instruction on the github page. :-( 

I can now run this on my iphone, but for some reason i cannot connect to the device. The handler i pass to the connectWithHandler method on device never gets called.

**Comment by ravimbhatt** [comment]
here is my code to connect to a device ... 

self.device!.connectWithTimeout(45, handler: { (error:NSError?) -> Void in
            print(error!)
            self.device!.led?.flashLEDColor(UIColor(red: 1.0, green: 0.0, blue: 0.0, alpha: 1.0), withIntensity: 1.0)
        })

even after giving 45 secs connection time. I cannot connect to the device and the handler code never gets invoked. 

If i call this a second time, the handler code gets called but show connection timeout error. The metawear app connects to the device fine but not my app. Anything i am missing here?

**Comment by sschiffli** [comment]
Let me answer this with code.  I'll add relevant scanning and connecting code to this repository to help jump start your development.

**Comment by ravimbhatt** [comment]
cool thanks. That would be awesome. 

For some reason, metawear app detects and connects with the boards fine but no lock with the code in swift. i can detect the boards and get their UUIDs but cannot connect. Connection always fails.

**Comment by sschiffli** [comment]
Check out the latest push.  It contains all the necessary code to scan and connect to MetaWear's.
